apiVersion: apps/v1
kind: Deployment
metadata:
  name: history
  namespace: godzilla
  labels:
    app: history
spec:
  replicas: 1
  selector:
    matchLabels:
      app: history
  template:
    metadata:
      labels:
        app: history
    spec:
      containers:
      - name: history
        image: history:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: MONGODB_URI
          value: "mongodb://mongodb:27017"
        - name: DATABASE_NAME
          value: "godzilla"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: history-svc
  namespace: godzilla
spec:
  selector:
    app: history
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP