apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: godzilla-cert
  namespace: godzilla
spec:
  domains:
    - godzilla.adri.ovh
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: godzilla-ingress
  namespace: godzilla
  annotations:
    networking.gke.io/managed-certificates: godzilla-cert
    kubernetes.io/ingress.global-static-ip-name: godzilla-ip
    kubernetes.io/ingress.class: "gce"
    external-dns.alpha.kubernetes.io/hostname: godzilla.adri.ovh
spec:
  rules:
    - host: godzilla.adri.ovh
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gateway-svc
                port:
                  number: 80
